apiVersion: v1
kind: Service
metadata:
  name: wohlig-agents
  namespace: pocketstudio-prod
  labels:
    app: wohlig-agents
spec:
  type: ClusterIP
  selector:
    app: wohlig-agents
  ports:
    - port: 3100
      targetPort: 3100
      name: http
